version: '3.6'

services:
  rabbitmq:
    image: "rabbitmq:3.10-management"
    container_name: rabbitmq
    restart: always
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: leogiraldimg
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"

